### PR TITLE
added TinyStr16

### PR DESCRIPTION
**Pull request by BartMassey**
This is the dumbest possible fast copy-paste to get `TinyStr16`. If you would like I can factor all this so that there's little copy-paste coding, but that's a much bigger job. This would also easily allow `TinyStr2`, which might also be a thing in some applications?

### CODE REVIEW

**Comment by BartMassey** [comment]
> I'm struggling to think of a valid use case for TinyStr2.

`troff` :-)

**Comment by zbraniecki** [comment]
@BartMassey thanks for the PR! Would you be open to add benchmarks for it?

**Comment by BartMassey** [comment]
OK, I added the benchmarks. I also cleaned up the benchmark code quite a bit with macros so that it's shorter and less error-prone. There's still much that could be done there, but I got done working on it before it all really finished.

In the process I found a couple of apparently-missing `black_box()` calls. Sadly, I think they affect the benchmark results. I'll leave it to you to take it from here.

**Comment by zbraniecki** [comment]
That's awesome! Thank you! I'll update the perf numbers :)

**Pull request merged**
